# Don't print a new line at the start of the prompt
add_newline = false
# Pipes ‚ï∞‚îÄ ‚ï≠‚îÄ
# Powerline symbols ¬†ÓÇ∞ ÓÇ± ÓÇ≤ ÓÇ≥ ÓÇ¥ ÓÇµ ÓÇ∂ ÓÇ∑ ÓÇ∏ ÓÇπ ÓÇ∫ ÓÇª ÓÇº ÓÇΩ ÓÇæ ÓÇø ÓÉÄ ÓÉÅ ÓÉÇ ÓÉÉ ÓÉÑ ÓÉÖ ÓÉÜ ÓÉá ÓÉà ÓÉä  ÓÉå ÓÉç ÓÉé ÓÉè ÓÉê ÓÉë ÓÉî ÓÉí 
# Wedges ü≠ßü≠í ü≠£ü≠ßü≠ì
# Random noise ü¨ñü¨•ü¨îü¨ó

# format = """
# $cmd_duration$username$hostname $directory $git_branch
# $character
# """
format = """
$cmd_duration Û∞ú• $directory $git_branch$git_status $username$hostname$all $nodejs${custom.nextjs} ${custom.typescript}${custom.react}${custom.tailwind}

$character
"""

# Replace the "‚ùØ" symbol in the prompt with "‚ûú"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[ Û∞ú• ÔÅã](bold fg:blue)"
error_symbol = "[ Û∞ú• ÔÄç](bold fg:red)"

# Disable the package module, hiding it from the prompt completely

[git_branch]
style = "bg: cyan"
symbol = "Û∞ò¨"
truncation_symbol = ""
format = "Û∞ú• [ÓÇ∂](bold fg:cyan)[$symbol $branch(:$remote_branch)](fg:black bg:cyan)[ÓÇ¥ ](bold fg:cyan)"

[git_commit]
commit_hash_length = 4
tag_symbol = "Ôí∂ "

[git_state]
format = '($state( $progress_current of $progress_total))($style)'
cherry_pick = "[üçí PICKING](bold red)"

[git_status]
conflicted = " üè≥ "
ahead = " üèéüí® "
behind = " üò∞ "
diverged = " Û±°∑ "
untracked = " Û∞éî "
stashed = " Û∞Üì "
modified = " Ó´û "
staged = '[++\($count\)](green)'
renamed = " Ó´† "
deleted = " üóë "

[hostname]
ssh_only = false
format =  "[‚Ä¢$hostname](bg:cyan bold fg:black)[ÓÇ¥](bold fg:cyan) "
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = true

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = 'üïô[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:cyan fg:black"
style_root = "red bold"
format = "[ÓÇ∂](bold fg:cyan)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " Ôë≠ "
read_only = " Ôëñ "
style = "bg:green fg:black"
truncation_length = 6
truncation_symbol = " ‚Ä¢‚Ä¢/"
format = '[ÓÇ∂](bold fg:green)[Û∞âã Ó™∂$path]($style)[ÓÇ¥](bold fg:green)'


[directory.substitutions]
"Desktop" = " Ôí© "
"Documents" = " Ôí• "
"Downloads" = " Ôêâ "
"Music" = " Û∞éà "
"Pictures" = " Ôêè "
"Videos" = " Ôî¨ "
"GitHub" = " Û∞ä§ "

[cmd_duration]
min_time = 0
format = '[ÓÇ∂](bold fg:yellow)[Û∞™¢ $duration](bold bg:yellow fg:black)[ÓÇ¥](bold fg:yellow)'

[bun]
format = 'via [üçî $version](bold green) '

[c]
symbol = "Óù± "

[cobol]
symbol = "cobol "

[conda]
symbol = "conda "

[crystal]
symbol = "cr "

[cmake]
symbol = "Óûî "

[daml]
symbol = "daml "

[dart]
symbol = "Óôå  "

[deno]
symbol = "ÓüÄ "

[dotnet]
symbol = "Û∞™Æ  "


[docker_context]
symbol = " Ôåà "

[elixir]
symbol = " Óò≠ "

[elm]
symbol = "elm "


[golang]
symbol = " Û∞üì "

[guix_shell]
symbol = " Ôå• "

[hg_branch]
symbol = "hg "

[java]
symbol = " Óâñ "

[julia]
symbol = " Óò§ "

[kotlin]
symbol = " Û±àô "

[lua]
symbol = " Ó†¶ "

[nodejs]
symbol = "Û∞éô "

[meson]
symbol = "meson "

[nim]
symbol = "nim "

[nix_shell]
symbol = " Ôåì "

[ocaml]
symbol = "ml "

[opa]
symbol = "opa "

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = " Û∞£á "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[package]
symbol = " Û∞èó "

[perl]
symbol = " Óôæ "

[php]
symbol = " Óòà "

[pulumi]
symbol = "pulumi "

[purescript]
symbol = "purs "

[python]
symbol = " Óàµ "

[raku]
symbol = "raku "

[ruby]
symbol = " Óúπ "

[rust]
symbol = " Û±òó "

[scala]
symbol = "scala "

[spack]
symbol = "spack "

[sudo]
symbol = "sudo "

[swift]
symbol = "Óöô "

[terraform]
symbol = "terraform "

[zig]
symbol = " Óö© "


[battery]
full_symbol = 'üîã '
charging_symbol = '‚ö°Ô∏è '

[[battery.display]]
threshold = 30
style = 'bold red'

[buf]
symbol = 'ü¶¨ '

[custom.react]
# We wrap the logic in "sh -c" so Fish doesn't try to parse the Bash syntax.
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"react\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "on Óû∫ v$ver"
  fi
fi
'
'''
detect_files = ['package.json']
format = '[$output ](bold blue)'

[custom.typescript]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"typescript\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "via Ó£ä v$ver"
    exit 0
  fi
fi
if ls *.ts *.tsx >/dev/null 2>&1; then
  echo "via Ó£ä v$(tsc --version | cut -d \" \" -f 2)"
fi
'
'''
detect_files = ['package.json', 'tsconfig.json']
detect_extensions = ['ts', 'tsx']
format = '[$output ](bold blue)'


[custom.nextjs]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"next\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "using Ó†æ v$ver"
  fi
fi
'
'''
detect_files = ['next.config.js', 'next.config.mjs', 'package.json']
format = '[$output ](bold white)'



[custom.tailwind]
command = '''
sh -c '
if [ -f package.json ]; then
  ver=$(grep "\"tailwindcss\":" package.json | head -n1 | sed -E "s/.*: *\"([^\"]*)\".*/\1/" | sed "s/[\^~]//g")
  if [ -n "$ver" ]; then
    echo "with Û±èø v$ver"
  fi
fi
'
'''
detect_files = ['tailwind.config.js', 'tailwind.config.cjs', 'tailwind.config.mjs', 'tailwind.config.ts','package.json']
format = '[$output ](bold cyan)'
